In [32]:
import numpy as np
import pandas as pd
import feather

In [33]:
tmp_items = feather.read_dataframe('tmp_items.feather')

In [34]:
#tmp_items['max_value'] = tmp_items['max_value'].apply(lambda x: float(x), 1)

In [35]:
tmp_items

,itemid,property,vol,num_values,max_value,min_value,time_avg
0,0,1036,1,1,1276750,1276750,1.433646e+12
1,0,1056,1,1,n3.168 1144008,n3.168 1144008,1.433041e+12
2,0,11,1,1,n15360.000 628176 n12288.000,n15360.000 628176 n12288.000,1.433646e+12
3,0,112,1,1,679677,679677,1.433646e+12
4,0,127,1,1,1168476,1168476,1.433041e+12
5,0,139,1,1,n4800.000 270060 924073,n4800.000 270060 924073,1.432436e+12
6,0,159,1,1,519769,519769,1.431227e+12
7,0,177,1,1,n96.000 1206660,n96.000 1206660,1.433646e+12
8,0,189,1,1,708480,708480,1.435460e+12
9,0,202,1,1,478989,478989,1.432436e+12
10,0,225,1,1,1301326,1301326,1.431832e+12
11,0,227,1,1,1152934 1238769,1152934 1238769,1.434251e+12
12,0,283,1,1,66094 372274 478989,66094 372274 478989,1.431227e+12
13,0,364,1,1,20716,20716,1.435460e+12
14,0,42,1,1,n204.000,n204.000,1.435460e+12
15,0,561,1,1,1294803 101489,1294803 101489,1.433041e+12
16,0,6,18,2,66094,1152934 1238769,1.436771e+12
17,0,678,1,1,372274,372274,1.431227e+12
18,0,698,1,1,1152934 1238769,1152934 1238769,1.431832e+12
19,0,764,1,1,1285872,1285872,1.433041e+12
20,0,776,1,1,318611,318611,1.432436e+12
21,0,790,1,1,n91200.000,n91200.000,1.431227e+12
22,0,839,1,1,372274,372274,1.432436e+12
23,0,869,1,1,769062,769062,1.433041e+12
24,0,888,1,1,478989,478989,1.433041e+12
25,0,917,1,1,478989,478989,1.435460e+12
26,0,available,1,1,0,0,1.431832e+12
27,0,categoryid,1,1,209,209,1.431227e+12
28,1,0,1,1,769062,769062,1.434251e+12
29,1,1036,1,1,1154859,1154859,1.433646e+12
...,...,...,...,...,...,...,...
12003784,466866,341,1,1,769062,769062,1.431832e+12
12003785,466866,348,1,1,769062,769062,1.435460e+12
12003786,466866,364,1,1,30965,30965,1.433646e+12
12003787,466866,521,1,1,769062,769062,1.433041e+12
12003788,466866,593,1,1,670753 114844 808585 1169076 837589,670753 114844 808585 1169076 837589,1.435460e+12
12003789,466866,594,1,1,892415 670753 114844 808585 769062,892415 670753 114844 808585 769062,1.431832e+12
12003790,466866,6,1,1,579062 353870,579062 353870,1.431227e+12
12003791,466866,642,1,1,769062,769062,1.432436e+12
12003792,466866,643,1,1,670753,670753,1.432436e+12
12003793,466866,678,1,1,892415,892415,1.433041e+12
12003794,466866,689,1,1,150169 615233 16718,150169 615233 16718,1.431832e+12
12003795,466866,698,1,1,579062 353870,579062 353870,1.439694e+12
12003796,466866,706,1,1,892415 670753 114844 808585,892415 670753 114844 808585,1.433646e+12
12003797,466866,711,1,1,1228055,1228055,1.433646e+12
12003798,466866,732,1,1,579062 353870,579062 353870,1.432436e+12
12003799,466866,739,1,1,579062 353870 1284577 579062 353870,579062 353870 1284577 579062 353870,1.434251e+12
12003800,466866,756,1,1,769062,769062,1.439694e+12
12003801,466866,764,1,1,1285872,1285872,1.431227e+12
12003802,466866,772,1,1,769062,769062,1.431832e+12
12003803,466866,776,1,1,550800,550800,1.431227e+12
12003804,466866,790,1,1,n13320.000,n13320.000,1.431227e+12
12003805,466866,850,1,1,670753 114844 808585 1169076,670753 114844 808585 1169076,1.431227e+12
12003806,466866,873,1,1,892415 385767,892415 385767,1.439694e+12
12003807,466866,876,1,1,1322342 945042 150169 1252290,1322342 945042 150169 1252290,1.433646e+12
12003808,466866,886,1,1,769062,769062,1.433041e+12
12003809,466866,888,1,1,892415 670753 114844 808585,892415 670753 114844 808585,1.431227e+12
12003810,466866,896,1,1,769062,769062,1.433041e+12
12003811,466866,917,1,1,89667,89667,1.431227e+12
12003812,466866,available,1,1,0,0,1.432436e+12
12003813,466866,categoryid,1,1,1164,1164,1.433041e+12

In [36]:
#tmp_items_cast = tmp_items.pivot_table(values = 'max_value', index = [tmp_items.index.values,'itemid'], columns = 'property', aggfunc = np.max).reset_index('itemid')

In [37]:
#tmp_items_cast = tmp_items.pivot_table(index = 'itemid',columns = 'property', values = 'max_value', aggfunc = np.max,# margins = False)

In [38]:
tmp_items = tmp_items[['itemid','property','max_value']]

In [39]:
tmp_items = tmp_items.groupby(['itemid','property'], as_index = False)['max_value'].max()

# Just so we don't have to do all that again...

In [41]:
feather.write_dataframe(df=tmp_items,path='tmp_items_rewrite.feather')

In [47]:
tmp_items['max_value'] = tmp_items['max_value'].fillna(0)

In [ ]:
max_property_vals = tmp_items.groupby('property')['max_value'].max()

In [12]:
tmp_items = tmp_items.set_index(['itemid','property'])

In [17]:
tmp_items_cast = tmp_items.unstack(level=1)

In [24]:
tmp_items_cast = tmp_items_cast.reset_index()

TypeError: cannot insert an item into a CategoricalIndex that is not already an existing category

In [22]:
tmp_items_cast[tmp_items_cast['itemid'] == '1']

KeyError: 'itemid'